#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>
#include "riscv_verilog.h"

void verilog_config_default(VerilogConfig *cfg) {
    memset(cfg, 0, sizeof(VerilogConfig));
    cfg->standard    = VERILOG_2001;
    cfg->control     = CTRL_HARDWIRED;
    cfg->hazard      = HAZARD_FULL_FWD;
    cfg->addr_width  = 32;
    cfg->data_width  = 32;
    cfg->include_imem = true;
    cfg->include_dmem = true;
    cfg->include_debug = false;
    cfg->include_uart  = false;
    cfg->include_csr   = true;
    cfg->include_fpu   = false;
    cfg->single_cycle  = false;
    cfg->multi_cycle   = false;
    cfg->pipeline      = true;
    cfg->out_of_order  = false;
    strcpy(cfg->module_name, "riscv_core");
    strcpy(cfg->top_module,  "riscv_top");
}

void verilog_writer_init(VerilogWriter *vw, const char *path,
                         const VerilogConfig *cfg) {
    memset(vw, 0, sizeof(VerilogWriter));
    vw->cfg = *cfg;
    vw->fp  = fopen(path, "w");
    if (!vw->fp) {
        fprintf(stderr, "Error: cannot open %s for writing\n", path);
        return;
    }
    vw->indent_level = 0;
    vw->line_count   = 0;
}

void verilog_writer_close(VerilogWriter *vw) {
    if (vw->fp) {
        fclose(vw->fp);
        vw->fp = NULL;
    }
}

static void emit_indent(VerilogWriter *vw) {
    for (uint32_t i = 0; i < vw->indent_level; i++)
        fputs("    ", vw->fp);
}

void verilog_comment(VerilogWriter *vw, const char *fmt, ...) {
    if (!vw->fp) return;
    emit_indent(vw);
    fputs("// ", vw->fp);
    va_list args;
    va_start(args, fmt);
    vfprintf(vw->fp, fmt, args);
    va_end(args);
    fputc('\n', vw->fp);
    vw->line_count++;
}

void verilog_stmt(VerilogWriter *vw, const char *fmt, ...) {
    if (!vw->fp) return;
    emit_indent(vw);
    va_list args;
    va_start(args, fmt);
    vfprintf(vw->fp, fmt, args);
    va_end(args);
    if (fmt[strlen(fmt) - 1] != '\n') fputc('\n', vw->fp);
    vw->line_count++;
}

void verilog_indent(VerilogWriter *vw) {
    vw->indent_level++;
}

void verilog_dedent(VerilogWriter *vw) {
    if (vw->indent_level > 0) vw->indent_level--;
}

void verilog_emit_header(VerilogWriter *vw) {
    if (!vw->fp) return;
    fprintf(vw->fp, "// ============================================\n");
    fprintf(vw->fp, "//  RISC-V RV32I Processor - Verilog RTL\n");
    fprintf(vw->fp, "//  Generated by mini-riscv-arch\n");
    fprintf(vw->fp, "//  Standard: Verilog-2001\n");
    fprintf(vw->fp, "// ============================================\n\n");
    vw->line_count += 5;
}

void verilog_emit_footer(VerilogWriter *vw) {
    if (!vw->fp) return;
    fprintf(vw->fp, "\nendmodule\n");
    vw->line_count += 2;
}

void verilog_emit_module_decl(VerilogWriter *vw, const char *name,
                              const char **ports, uint32_t port_count) {
    if (!vw->fp) return;
    fprintf(vw->fp, "module %s ", name);
    if (port_count > 0) {
        fprintf(vw->fp, "(\n");
        for (uint32_t i = 0; i < port_count; i++) {
            fprintf(vw->fp, "    %s", ports[i]);
            if (i < port_count - 1) fputs(",\n", vw->fp);
            else fputs("\n", vw->fp);
        }
        fprintf(vw->fp, ");\n");
    } else {
        fprintf(vw->fp, "();\n");
    }
    vw->line_count += 3 + port_count;
}

void verilog_emit_ports(VerilogWriter *vw, const char **inputs,
                        uint32_t in_count, const char **outputs,
                        uint32_t out_count) {
    if (!vw->fp) return;

    for (uint32_t i = 0; i < in_count; i++) {
        fprintf(vw->fp, "    input  wire %s;\n", inputs[i]);
    }
    for (uint32_t i = 0; i < out_count; i++) {
        fprintf(vw->fp, "    output wire %s;\n", outputs[i]);
    }
    vw->line_count += in_count + out_count;
}

void verilog_emit_wire(VerilogWriter *vw, const char *name, uint32_t width) {
    if (!vw->fp) return;
    emit_indent(vw);
    if (width > 1)
        fprintf(vw->fp, "wire [%u:0] %s;\n", width - 1, name);
    else
        fprintf(vw->fp, "wire %s;\n", name);
    vw->line_count++;
}

void verilog_emit_reg(VerilogWriter *vw, const char *name, uint32_t width) {
    if (!vw->fp) return;
    emit_indent(vw);
    if (width > 1)
        fprintf(vw->fp, "reg [%u:0] %s;\n", width - 1, name);
    else
        fprintf(vw->fp, "reg %s;\n", name);
    vw->line_count++;
}

void verilog_emit_assign(VerilogWriter *vw, const char *lhs, const char *rhs) {
    if (!vw->fp) return;
    emit_indent(vw);
    fprintf(vw->fp, "assign %s = %s;\n", lhs, rhs);
    vw->line_count++;
}

void verilog_emit_always_comb_begin(VerilogWriter *vw) {
    if (!vw->fp) return;
    emit_indent(vw);
    fprintf(vw->fp, "always @(*) begin\n");
    vw->line_count++;
    vw->indent_level++;
}

void verilog_emit_always_ff_begin(VerilogWriter *vw, const char *edge,
                                  const char *clock) {
    if (!vw->fp) return;
    emit_indent(vw);
    fprintf(vw->fp, "always @(%s %s) begin\n", edge, clock);
    vw->line_count++;
    vw->indent_level++;
}

void verilog_emit_always_end(VerilogWriter *vw) {
    if (!vw->fp) return;
    vw->indent_level--;
    emit_indent(vw);
    fprintf(vw->fp, "end\n");
    vw->line_count++;
}

void verilog_emit_if_begin(VerilogWriter *vw, const char *cond) {
    if (!vw->fp) return;
    emit_indent(vw);
    fprintf(vw->fp, "if (%s) begin\n", cond);
    vw->line_count++;
    vw->indent_level++;
}

void verilog_emit_if_end(VerilogWriter *vw) {
    if (!vw->fp) return;
    vw->indent_level--;
    emit_indent(vw);
    fprintf(vw->fp, "end\n");
    vw->line_count++;
}

void verilog_emit_case_begin(VerilogWriter *vw, const char *sel) {
    if (!vw->fp) return;
    emit_indent(vw);
    fprintf(vw->fp, "case (%s)\n", sel);
    vw->line_count++;
    vw->indent_level++;
}

void verilog_emit_case_item(VerilogWriter *vw, const char *value) {
    if (!vw->fp) return;
    emit_indent(vw);
    fprintf(vw->fp, "%s: begin\n", value);
    vw->line_count++;
    vw->indent_level++;
}

void verilog_emit_case_end(VerilogWriter *vw) {
    if (!vw->fp) return;
    vw->indent_level--;
    emit_indent(vw);
    fprintf(vw->fp, "endcase\n");
    vw->line_count++;
}

void verilog_emit_pc_logic(VerilogWriter *vw) {
    if (!vw->fp) return;
    verilog_comment(vw, "PC Logic");
    verilog_emit_reg(vw, "pc", 32);
    verilog_emit_reg(vw, "pc_next", 32);
    verilog_stmt(vw, "");
    verilog_emit_always_ff_begin(vw, "posedge", "clk");
    verilog_emit_if_begin(vw, "!rst_n");
    verilog_stmt(vw, "pc <= 32'h00000000;");
    verilog_emit_if_end(vw);
    verilog_stmt(vw, "else begin");
    vw->indent_level++;
    verilog_stmt(vw, "pc <= pc_next;");
    vw->indent_level--;
    verilog_stmt(vw, "end");
    verilog_emit_always_end(vw);
}

void verilog_emit_imem(VerilogWriter *vw, uint32_t depth) {
    if (!vw->fp) return;
    verilog_comment(vw, "Instruction Memory");
    verilog_stmt(vw, "reg [31:0] imem [0:%u];", depth - 1);
    verilog_stmt(vw, "wire [31:0] inst;");
    verilog_stmt(vw, "");
    verilog_emit_assign(vw, "inst", "imem[pc[%u:2]]", (uint32_t)31);
}

void verilog_emit_register_file(VerilogWriter *vw) {
    if (!vw->fp) return;
    verilog_comment(vw, "Register File (x0 hardwired to 0)");
    verilog_stmt(vw, "reg [31:0] rf [31:0];");
    verilog_stmt(vw, "wire [31:0] rs1_data, rs2_data;");
    verilog_stmt(vw, "wire [31:0] wb_data;");
    verilog_stmt(vw, "");
    verilog_emit_assign(vw, "rs1_data", "(rs1_addr == 5'd0) ? 32'd0 : rf[rs1_addr]");
    verilog_emit_assign(vw, "rs2_data", "(rs2_addr == 5'd0) ? 32'd0 : rf[rs2_addr]");
    verilog_stmt(vw, "");
    verilog_emit_always_ff_begin(vw, "posedge", "clk");
    verilog_emit_if_begin(vw, "wb_en && (rd_addr != 5'd0)");
    verilog_stmt(vw, "rf[rd_addr] <= wb_data;");
    verilog_emit_if_end(vw);
    verilog_emit_always_end(vw);
}

void verilog_emit_alu(VerilogWriter *vw) {
    if (!vw->fp) return;
    verilog_comment(vw, "ALU");
    verilog_stmt(vw, "reg [31:0] alu_result;");
    verilog_stmt(vw, "wire [31:0] alu_a, alu_b;");
    verilog_stmt(vw, "wire [3:0] alu_op;");
    verilog_stmt(vw, "");
    verilog_emit_always_comb_begin(vw);
    verilog_emit_case_begin(vw, "alu_op");
    verilog_emit_case_item(vw, "4'd0");
    verilog_stmt(vw, "alu_result = alu_a + alu_b;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "4'd1");
    verilog_stmt(vw, "alu_result = alu_a - alu_b;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "4'd2");
    verilog_stmt(vw, "alu_result = alu_a << alu_b[4:0];");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "4'd3");
    verilog_stmt(vw, "alu_result = ($signed(alu_a) < $signed(alu_b)) ? 32'd1 : 32'd0;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "4'd4");
    verilog_stmt(vw, "alu_result = (alu_a < alu_b) ? 32'd1 : 32'd0;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "4'd5");
    verilog_stmt(vw, "alu_result = alu_a ^ alu_b;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "4'd6");
    verilog_stmt(vw, "alu_result = alu_a >> alu_b[4:0];");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "4'd7");
    verilog_stmt(vw, "alu_result = $signed(alu_a) >>> alu_b[4:0];");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "4'd8");
    verilog_stmt(vw, "alu_result = alu_a | alu_b;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "4'd9");
    verilog_stmt(vw, "alu_result = alu_a & alu_b;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "default");
    verilog_stmt(vw, "alu_result = 32'd0;");
    verilog_emit_case_end(vw);
    verilog_emit_case_end(vw);
    verilog_emit_always_end(vw);
}

void verilog_emit_dmem(VerilogWriter *vw, uint32_t depth) {
    if (!vw->fp) return;
    verilog_comment(vw, "Data Memory");
    verilog_stmt(vw, "reg [31:0] dmem [0:%u];", depth - 1);
    verilog_stmt(vw, "wire [31:0] dmem_rdata;");
    verilog_stmt(vw, "");
    verilog_emit_assign(vw, "dmem_rdata", "dmem[mem_addr[%u:2]]", (uint32_t)31);
    verilog_stmt(vw, "");
    verilog_emit_always_ff_begin(vw, "posedge", "clk");
    verilog_emit_if_begin(vw, "mem_write");
    verilog_stmt(vw, "dmem[mem_addr[%u:2]] <= mem_wdata;", (uint32_t)31);
    verilog_emit_if_end(vw);
    verilog_emit_always_end(vw);
}

void verilog_emit_wb_mux(VerilogWriter *vw) {
    if (!vw->fp) return;
    verilog_comment(vw, "Writeback Mux");
    verilog_stmt(vw, "reg [31:0] wb_mux_out;");
    verilog_stmt(vw, "");
    verilog_emit_always_comb_begin(vw);
    verilog_emit_case_begin(vw, "wb_sel");
    verilog_emit_case_item(vw, "2'd0");
    verilog_stmt(vw, "wb_mux_out = alu_result;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "2'd1");
    verilog_stmt(vw, "wb_mux_out = dmem_rdata;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "2'd2");
    verilog_stmt(vw, "wb_mux_out = pc_plus_4;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "2'd3");
    verilog_stmt(vw, "wb_mux_out = imm;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "default");
    verilog_stmt(vw, "wb_mux_out = alu_result;");
    verilog_emit_case_end(vw);
    verilog_emit_case_end(vw);
    verilog_emit_always_end(vw);
}

void verilog_emit_control_fsm(VerilogWriter *vw) {
    if (!vw->fp) return;
    verilog_comment(vw, "Control FSM States");
    verilog_stmt(vw, "localparam S_IF   = 3'd0;");
    verilog_stmt(vw, "localparam S_ID   = 3'd1;");
    verilog_stmt(vw, "localparam S_EX   = 3'd2;");
    verilog_stmt(vw, "localparam S_MEM  = 3'd3;");
    verilog_stmt(vw, "localparam S_WB   = 3'd4;");
    verilog_stmt(vw, "");
    verilog_emit_reg(vw, "state", 3);
    verilog_emit_reg(vw, "next_state", 3);
    verilog_stmt(vw, "");
    verilog_emit_always_ff_begin(vw, "posedge", "clk");
    verilog_emit_if_begin(vw, "!rst_n");
    verilog_stmt(vw, "state <= S_IF;");
    verilog_emit_if_end(vw);
    verilog_stmt(vw, "else begin");
    vw->indent_level++;
    verilog_stmt(vw, "state <= next_state;");
    vw->indent_level--;
    verilog_stmt(vw, "end");
    verilog_emit_always_end(vw);
    verilog_stmt(vw, "");
    verilog_emit_always_comb_begin(vw);
    verilog_emit_case_begin(vw, "state");
    verilog_emit_case_item(vw, "S_IF");
    verilog_stmt(vw, "next_state = stall ? S_IF : S_ID;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "S_ID");
    verilog_stmt(vw, "next_state = stall ? S_ID : S_EX;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "S_EX");
    verilog_stmt(vw, "next_state = S_MEM;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "S_MEM");
    verilog_stmt(vw, "next_state = S_WB;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "S_WB");
    verilog_stmt(vw, "next_state = S_IF;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "default");
    verilog_stmt(vw, "next_state = S_IF;");
    verilog_emit_case_end(vw);
    verilog_emit_case_end(vw);
    verilog_emit_always_end(vw);
}

void verilog_emit_control_hardwired(VerilogWriter *vw) {
    if (!vw->fp) return;
    verilog_comment(vw, "Hardwired Control Signals");
    verilog_stmt(vw, "reg  reg_write;");
    verilog_stmt(vw, "reg  mem_read;");
    verilog_stmt(vw, "reg  mem_write;");
    verilog_stmt(vw, "reg  branch;");
    verilog_stmt(vw, "reg  jump;");
    verilog_stmt(vw, "reg  jalr;");
    verilog_stmt(vw, "reg [3:0] alu_op;");
    verilog_stmt(vw, "reg [1:0] alu_src_a;");
    verilog_stmt(vw, "reg [2:0] alu_src_b;");
    verilog_stmt(vw, "reg [1:0] wb_sel;");
    verilog_stmt(vw, "");
    verilog_emit_always_comb_begin(vw);
    verilog_stmt(vw, "reg_write  = 1'b0;");
    verilog_stmt(vw, "mem_read   = 1'b0;");
    verilog_stmt(vw, "mem_write  = 1'b0;");
    verilog_stmt(vw, "branch     = 1'b0;");
    verilog_stmt(vw, "jump       = 1'b0;");
    verilog_stmt(vw, "alu_op     = 4'd0;");
    verilog_stmt(vw, "alu_src_a  = 2'd0;");
    verilog_stmt(vw, "alu_src_b  = 3'd0;");
    verilog_stmt(vw, "wb_sel     = 2'd0;");
    verilog_stmt(vw, "");
    verilog_emit_case_begin(vw, "opcode");
    verilog_emit_case_item(vw, "7'b0110011");
    verilog_stmt(vw, "reg_write = 1'b1; alu_src_b = 3'd1; wb_sel = 2'd0;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "7'b0010011");
    verilog_stmt(vw, "reg_write = 1'b1; alu_src_b = 3'd2; wb_sel = 2'd0;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "7'b0000011");
    verilog_stmt(vw, "reg_write = 1'b1; mem_read = 1'b1; alu_src_b = 3'd2; wb_sel = 2'd1;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "7'b0100011");
    verilog_stmt(vw, "mem_write = 1'b1; alu_src_b = 3'd2;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "7'b1100011");
    verilog_stmt(vw, "branch = 1'b1; alu_src_b = 3'd1;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "7'b1101111");
    verilog_stmt(vw, "reg_write = 1'b1; jump = 1'b1; wb_sel = 2'd2;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "7'b1100111");
    verilog_stmt(vw, "reg_write = 1'b1; jalr = 1'b1; alu_src_b = 3'd2; wb_sel = 2'd2;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "7'b0110111");
    verilog_stmt(vw, "reg_write = 1'b1; wb_sel = 2'd3;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "7'b0010111");
    verilog_stmt(vw, "reg_write = 1'b1; alu_src_a = 2'd1; alu_src_b = 3'd2; wb_sel = 2'd0;");
    verilog_emit_case_end(vw);
    verilog_emit_case_end(vw);
    verilog_emit_always_end(vw);
}

void verilog_emit_hazard_unit(VerilogWriter *vw) {
    if (!vw->fp) return;
    verilog_comment(vw, "Hazard Detection Unit");
    verilog_stmt(vw, "reg stall;");
    verilog_stmt(vw, "reg flush;");
    verilog_stmt(vw, "reg [1:0] forward_a;");
    verilog_stmt(vw, "reg [1:0] forward_b;");
    verilog_stmt(vw, "");
    verilog_emit_always_comb_begin(vw);
    verilog_stmt(vw, "stall     = 1'b0;");
    verilog_stmt(vw, "flush     = 1'b0;");
    verilog_stmt(vw, "forward_a = 2'b00;");
    verilog_stmt(vw, "forward_b = 2'b00;");

    verilog_comment(vw, "Load-use hazard");
    verilog_emit_if_begin(vw, "ex_mem_reg_write && ex_mem_rd != 5'd0 && "
                              "id_ex_rs1 == ex_mem_rd");
    verilog_stmt(vw, "stall = 1'b1;");
    verilog_emit_if_end(vw);

    verilog_comment(vw, "Forwarding EX/MEM -> EX");
    verilog_emit_if_begin(vw, "ex_mem_reg_write && ex_mem_rd != 5'd0 && "
                              "ex_mem_rd == id_ex_rs1");
    verilog_stmt(vw, "forward_a = 2'b10;");
    verilog_emit_if_end(vw);
    verilog_emit_if_begin(vw, "ex_mem_reg_write && ex_mem_rd != 5'd0 && "
                              "ex_mem_rd == id_ex_rs2");
    verilog_stmt(vw, "forward_b = 2'b10;");
    verilog_emit_if_end(vw);

    verilog_comment(vw, "Forwarding MEM/WB -> EX");
    verilog_emit_if_begin(vw, "mem_wb_reg_write && mem_wb_rd != 5'd0 && "
                              "!(ex_mem_reg_write && ex_mem_rd != 5'd0 && "
                              "ex_mem_rd == id_ex_rs1) && mem_wb_rd == id_ex_rs1");
    verilog_stmt(vw, "forward_a = 2'b01;");
    verilog_emit_if_end(vw);
    verilog_emit_if_begin(vw, "mem_wb_reg_write && mem_wb_rd != 5'd0 && "
                              "!(ex_mem_reg_write && ex_mem_rd != 5'd0 && "
                              "ex_mem_rd == id_ex_rs2) && mem_wb_rd == id_ex_rs2");
    verilog_stmt(vw, "forward_b = 2'b01;");
    verilog_emit_if_end(vw);
    verilog_emit_always_end(vw);
}

void verilog_emit_forwarding_logic(VerilogWriter *vw) {
    if (!vw->fp) return;
    verilog_comment(vw, "Forwarding Multiplexers");
    verilog_stmt(vw, "reg [31:0] operand_a;");
    verilog_stmt(vw, "reg [31:0] operand_b;");
    verilog_stmt(vw, "");
    verilog_emit_always_comb_begin(vw);
    verilog_emit_case_begin(vw, "forward_a");
    verilog_emit_case_item(vw, "2'b00");
    verilog_stmt(vw, "operand_a = rs1_data;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "2'b01");
    verilog_stmt(vw, "operand_a = mem_wb_result;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "2'b10");
    verilog_stmt(vw, "operand_a = ex_mem_result;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "default");
    verilog_stmt(vw, "operand_a = rs1_data;");
    verilog_emit_case_end(vw);
    verilog_emit_case_end(vw);
    verilog_stmt(vw, "");
    verilog_emit_case_begin(vw, "forward_b");
    verilog_emit_case_item(vw, "2'b00");
    verilog_stmt(vw, "operand_b = rs2_data;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "2'b01");
    verilog_stmt(vw, "operand_b = mem_wb_result;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "2'b10");
    verilog_stmt(vw, "operand_b = ex_mem_result;");
    verilog_emit_case_end(vw);
    verilog_emit_case_item(vw, "default");
    verilog_stmt(vw, "operand_b = rs2_data;");
    verilog_emit_case_end(vw);
    verilog_emit_case_end(vw);
    verilog_emit_always_end(vw);
}

void verilog_emit_stall_logic(VerilogWriter *vw) {
    if (!vw->fp) return;
    verilog_comment(vw, "Stall Logic - Freeze PC and Flush ID/EX");
    verilog_stmt(vw, "wire pc_write;");
    verilog_stmt(vw, "wire if_id_write;");
    verilog_stmt(vw, "");
    verilog_emit_assign(vw, "pc_write", "~stall");
    verilog_emit_assign(vw, "if_id_write", "~stall");
    verilog_stmt(vw, "");
    verilog_emit_always_ff_begin(vw, "posedge", "clk");
    verilog_emit_if_begin(vw, "~stall");
    verilog_stmt(vw, "pc <= pc_next;");
    verilog_emit_if_end(vw);
    verilog_emit_always_end(vw);
}

void verilog_emit_csr_block(VerilogWriter *vw) {
    if (!vw->fp) return;
    verilog_comment(vw, "CSR Registers (M-mode)");
    verilog_stmt(vw, "reg [31:0] mstatus;");
    verilog_stmt(vw, "reg [31:0] mepc;");
    verilog_stmt(vw, "reg [31:0] mtvec;");
    verilog_stmt(vw, "reg [31:0] mcause;");
    verilog_stmt(vw, "reg [31:0] mie;");
    verilog_stmt(vw, "reg [31:0] mip;");
    verilog_stmt(vw, "reg [63:0] mcycle;");
    verilog_stmt(vw, "");
    verilog_emit_always_ff_begin(vw, "posedge", "clk");
    verilog_emit_if_begin(vw, "!rst_n");
    verilog_stmt(vw, "mstatus <= 32'h00001800;");
    verilog_stmt(vw, "mepc    <= 32'd0;");
    verilog_stmt(vw, "mtvec   <= 32'd0;");
    verilog_stmt(vw, "mcause  <= 32'd0;");
    verilog_stmt(vw, "mcycle  <= 64'd0;");
    verilog_emit_if_end(vw);
    verilog_stmt(vw, "else begin");
    vw->indent_level++;
    verilog_stmt(vw, "mcycle <= mcycle + 64'd1;");
    vw->indent_level--;
    verilog_stmt(vw, "end");
    verilog_emit_always_end(vw);
}

void verilog_emit_timer(VerilogWriter *vw) {
    if (!vw->fp) return;
    verilog_comment(vw, "Timer (mtime / mtimecmp)");
    verilog_stmt(vw, "reg [63:0] mtime;");
    verilog_stmt(vw, "reg [63:0] mtimecmp;");
    verilog_stmt(vw, "wire timer_interrupt;");
    verilog_stmt(vw, "");
    verilog_emit_assign(vw, "timer_interrupt", "mtime >= mtimecmp");
    verilog_stmt(vw, "");
    verilog_emit_always_ff_begin(vw, "posedge", "clk");
    verilog_emit_if_begin(vw, "!rst_n");
    verilog_stmt(vw, "mtime    <= 64'd0;");
    verilog_stmt(vw, "mtimecmp <= 64'hFFFFFFFFFFFFFFFF;");
    verilog_emit_if_end(vw);
    verilog_stmt(vw, "else begin");
    vw->indent_level++;
    verilog_stmt(vw, "mtime <= mtime + 64'd1;");
    vw->indent_level--;
    verilog_stmt(vw, "end");
    verilog_emit_always_end(vw);
}

void verilog_emit_pipeline_reg(VerilogWriter *vw, const char *name,
                               uint32_t width) {
    if (!vw->fp) return;
    verilog_stmt(vw, "reg [%u:0] %s;", width - 1, name);
}

void verilog_emit_datapath(VerilogWriter *vw) {
    if (!vw->fp) return;
    verilog_comment(vw, "========================================");
    verilog_comment(vw, "  RISC-V 5-Stage Pipeline Datapath");
    verilog_comment(vw, "  PC -> IMEM -> RegFile -> ALU -> DMEM -> WB");
    verilog_comment(vw, "========================================");
    verilog_stmt(vw, "");

    verilog_emit_pc_logic(vw);
    verilog_stmt(vw, "");
    verilog_emit_imem(vw, 1024);
    verilog_stmt(vw, "");
    verilog_emit_register_file(vw);
    verilog_stmt(vw, "");
    verilog_emit_alu(vw);
    verilog_stmt(vw, "");
    verilog_emit_dmem(vw, 1024);
    verilog_stmt(vw, "");
    verilog_emit_wb_mux(vw);
    verilog_stmt(vw, "");
    verilog_emit_control_hardwired(vw);
    verilog_stmt(vw, "");
    verilog_emit_hazard_unit(vw);
    verilog_stmt(vw, "");
    verilog_emit_forwarding_logic(vw);
    verilog_stmt(vw, "");
    verilog_emit_csr_block(vw);
    verilog_stmt(vw, "");
    verilog_emit_timer(vw);
}

void verilog_emit_top_module(VerilogWriter *vw, const VerilogConfig *cfg) {
    if (!vw->fp) return;

    const char *ports[] = {
        "input  wire        clk",
        "input  wire        rst_n",
        "output wire [31:0] pc_out",
        "output wire [31:0] inst_out"
    };
    verilog_emit_module_decl(vw, cfg->top_module, ports, 4);
    verilog_stmt(vw, "");

    verilog_emit_wire(vw, "clk", 1);
    verilog_emit_wire(vw, "rst_n", 1);
    verilog_emit_wire(vw, "pc_out", 32);
    verilog_emit_wire(vw, "inst_out", 32);
    verilog_stmt(vw, "");

    verilog_comment(vw, "Instantiate the RISC-V core");
    verilog_stmt(vw, "%s u_core (", cfg->module_name);
    verilog_stmt(vw, "    .clk      (clk),");
    verilog_stmt(vw, "    .rst_n    (rst_n),");
    verilog_stmt(vw, "    .pc       (pc_out),");
    verilog_stmt(vw, "    .inst     (inst_out)");
    verilog_stmt(vw, ");");
    verilog_emit_footer(vw);
}

void verilog_generate_processor(const char *path, const VerilogConfig *cfg) {
    if (!path || !cfg) return;

    VerilogWriter vw;
    verilog_writer_init(&vw, path, cfg);
    if (!vw.fp) return;

    verilog_emit_header(&vw);
    verilog_emit_top_module(&vw, cfg);
    verilog_writer_close(&vw);

    printf("Generated Verilog processor: %s (%u lines)\n",
           path, vw.line_count);
}

void verilog_generate_testbench(const char *path, const VerilogConfig *cfg) {
    if (!path || !cfg) return;

    FILE *fp = fopen(path, "w");
    if (!fp) {
        fprintf(stderr, "Error: cannot open %s for writing\n", path);
        return;
    }

    fprintf(fp, "// ============================================\n");
    fprintf(fp, "//  RISC-V Processor Testbench\n");
    fprintf(fp, "//  Generated by mini-riscv-arch\n");
    fprintf(fp, "// ============================================\n\n");

    fprintf(fp, "`timescale 1ns / 1ps\n\n");
    fprintf(fp, "module tb_%s;\n\n", cfg->top_module);
    fprintf(fp, "    reg        clk;\n");
    fprintf(fp, "    reg        rst_n;\n");
    fprintf(fp, "    wire [31:0] pc;\n");
    fprintf(fp, "    wire [31:0] inst;\n\n");

    fprintf(fp, "    %s uut (\n", cfg->top_module);
    fprintf(fp, "        .clk   (clk),\n");
    fprintf(fp, "        .rst_n (rst_n),\n");
    fprintf(fp, "        .pc    (pc),\n");
    fprintf(fp, "        .inst  (inst)\n");
    fprintf(fp, "    );\n\n");

    fprintf(fp, "    always #5 clk = ~clk;\n\n");

    fprintf(fp, "    initial begin\n");
    fprintf(fp, "        $dumpfile(\"tb_%s.vcd\");\n", cfg->top_module);
    fprintf(fp, "        $dumpvars(0, tb_%s);\n\n", cfg->top_module);
    fprintf(fp, "        clk   = 0;\n");
    fprintf(fp, "        rst_n = 0;\n");
    fprintf(fp, "        #20 rst_n = 1;\n\n");

    fprintf(fp, "        #200;\n");
    fprintf(fp, "        $display(\"Testbench complete. PC = %%h\", pc);\n");
    fprintf(fp, "        $finish;\n");
    fprintf(fp, "    end\n\n");

    fprintf(fp, "endmodule\n");

    fclose(fp);
    printf("Generated Verilog testbench: %s\n", path);
}
